KEYMAP_FOLDER = keyboards/ergodox_ez/glow/keymaps/keebab
.PHONY: %
%:
	-keymapviz -k ergodox_ez -t fancy -r $(KEYMAP_FOLDER)/keymap.c -c $(KEYMAP_FOLDER)/keymapviz.toml > /dev/null

SRC = matrix.c

CAPS_WORD_ENABLE = yes
WEBUSB_ENABLE = yes
ORYX_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
NKRO_ENABLE = yes
LTO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

MOUSEKEY_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
STENO_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_OVERRIDE_ENABLE = no
PROGRAMMABLE_BUTTON_ENABLE = no
LEADER_ENABLE = no
COMMAND_ENABLE = no 
CONSOLE_ENABLE = no 
TERMINAL_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
SLEEP_LED_ENABLE = no
BOOTMAGIC_ENABLE = no
API_SYSEX_ENABLE = no
QMK_SETTINGS = no
GRAVE_ESC_ENABLE = no
KEY_LOCK_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
UCIS_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no